name             'mesos-master'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures mesos-master'
long_description 'Installs/Configures mesos-master'
version          '0.1.0'
depends 'exhibitor'
depends 'mesos'
